version: "3"

services:
  onthemat-server:
    environment:
      NODE_ENV:
      POSTGRES_HOST:
      POSTGRES_PORT:
      JWT_SECRET:
      PAYPAL_CLIENT:
      PAYPAL_SECRET:
      OUTLOOK_AC:
      OUTLOOK_PASS:
      MONGO_USER:
      MONGO_PASSWORD:
      MONGO_DB:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      S3_BUCKET_NAME:
      S3_REGION:
    env_file:
      - docker.env
    depends_on:
      - onthemat-db
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "ztellaw/onthemat-server:latest"
    ports:
      - "8080:8080"
  onthemat-db:
    image: "postgres:13"
    environment:
      POSTGRES_PORT: 5432
    env_file:
      - docker.env
    ports:
      - "25432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
