FROM node:18.13
WORKDIR /usr/src/app
COPY . .
EXPOSE 8080
CMD yarn install && \
    yarn knex migrate:latest &&\
    yarn knex seed:run &&\
    mkdir uploads &&\
    cp ./serviceAccountKey.json ./dist &&\
    node ./dist/server.js
